### ISSUE TITLE
load_private_scripts_dir list_dir returns nil

### ISSUE THREAD

**Issue by dongmingsun** [tongpengfei/bin_inspector#1]
打开软件时提示：
![image](https://user-images.githubusercontent.com/26035945/197926154-f5bcac44-56c8-4d34-aa64-2810f3a72be3.png)

Debug错误：
```
version: 0.0.3
...0.3/BinInspector_win64_release_v0.0.3/scripts/helper.lua:446: load_private_scripts_dir list_dir returns nil, path:C:/Users/马赛克/AppData/Roaming/BinInspector/scripts
```

打开DLL，界面仍然是空白，没有加载任何DLL相关信息

**Comment by tongpengfei** [comment]
hi,您的目录是否是中文

发自我的iPhone

**Comment by dongmingsun** [comment]
是中文

**Comment by tongpengfei** [comment]
可能是中文路径的问题，目前不支持中文路径，麻烦把scripts/helper.lua下的这两行先屏掉，再试试吧
![image](https://user-images.githubusercontent.com/1949293/197928218-35f3407b-ccd9-48bf-ae7b-53d59596a6a3.png)

**Comment by tongpengfei** [comment]
hi, v0.0.4支持中文路径了

**Comment by dongmingsun** [comment]
验证是version: 0.0.3不支持中文的问题
Close issue
